# The web settings for the service (API and UI).
# It is best to have this run on localhost and use a reverse proxy to access Dimension.
web:
  port: 8184
  address: '0.0.0.0'

# Homeserver configuration
homeserver:
  # The domain name of the homeserver. This is used in many places, such as with go-neb
  # setups, to identify the homeserver.
  name: "t2bot.io"

  # The URL that Dimension, go-neb, and other services provisioned by Dimension should
  # use to access the homeserver with.
  clientServerUrl: "https://t2bot.io"

  # The URL that Dimension should use when trying to communicate with federated APIs on
  # the homeserver. If not supplied or left empty Dimension will try to resolve the address
  # through the normal federation process.
  #federationUrl: "https://t2bot.io:8448"

  # The URL that Dimension will redirect media requests to for downloading media such as
  # stickers. If not supplied or left empty Dimension will use the clientServerUrl.
  #mediaUrl: "https://t2bot.io"

  # The access token Dimension should use for miscellaneous access to the homeserver, and
  # for tracking custom sticker pack updates. This should be a user configured on the homeserver
  # and be dedicated to Dimension (create a user named "dimension" on your homeserver). For
  # information on how to acquire an access token, visit https://t2bot.io/docs/access_tokens
  accessToken: "something"

# These users can modify the integrations this Dimension supports.
# To access the admin interface, open Dimension in Element and click the settings icon.
admins:
  - "@someone:domain.com"

# IPs and CIDR ranges listed here will be blocked from being widgets.
# Note: Widgets may still be embedded with restricted content, although not through Dimension directly.
widgetBlacklist:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 127.0.0.0/8

database:
  # Where the database for Dimension is
  file: "dimension.db"

  # Where to store misc information for the utility bot account.
  botData: "dimension.bot.json"

# Display settings that apply to self-hosted go-neb instances
goneb:
  # The avatars to set for each bot. Usually these don't need to be changed, however if your homeserver
  # is not able to reach t2bot.io then you should specify your own here. To not use an avatar for a bot,
  # make the bot's avatar an empty string.
  avatars:
    giphy: "mxc://t2bot.io/c5eaab3ef0133c1a61d3c849026deb27"
    imgur: "mxc://t2bot.io/6749eaf2b302bb2188ae931b2eeb1513"
    github: "mxc://t2bot.io/905b64b3cd8e2347f91a60c5eb0832e1"
    wikipedia: "mxc://t2bot.io/7edfb54e9ad9e13fec0df22636feedf1"
    travisci: "mxc://t2bot.io/7f4703126906fab8bb27df34a17707a8"
    rss: "mxc://t2bot.io/aace4fcbd045f30afc1b4e5f0928f2f3"
    google: "mxc://t2bot.io/636ad10742b66c4729bf89881a505142"
    guggy: "mxc://t2bot.io/e7ef0ed0ba651aaf907655704f9a7526"
    echo: "mxc://t2bot.io/3407ff2db96b4e954fcbf2c6c0415a13"
    circleci: "mxc://t2bot.io/cf7d875845a82a6b21f5f66de78f6bee"
    jira: "mxc://t2bot.io/f4a38ebcc4280ba5b950163ca3e7c329"

# Settings for interacting with Telegram. Currently only applies for importing
# sticker packs from Telegram.
telegram:
  # Talk to @BotFather on Telegram to get a token
  botToken: "YourTokenHere"

# Custom sticker pack options.
# Largely based on https://github.com/turt2live/matrix-sticker-manager
stickers:
  # Whether or not to allow people to add custom sticker packs
  enabled: true

  # The sticker manager bot to promote
  stickerBot: "@stickers:t2bot.io"

  # The sticker manager URL to promote
  managerUrl: "https://stickers.t2bot.io"

# Settings for how Dimension is represented to the public
dimension:
  # This is where Dimension is accessible from clients. Be sure to set this
  # to your own Dimension instance.
  publicUrl: "https://dimension.example.org"

bigbluebutton:
  # The full base URL of the API of your BigBlueButton instance. The API is
  # used to create and join meetings.
  apiBaseUrl: "https://bbb.example.org/bigbluebutton/api"

  # The "shared secret" of your BigBlueButton instance. This is used to
  # authenticate to the API above.
  sharedSecret: "YourSharedSecretHere"

  # The title for BigBlueButton widgets that are generated by Dimension.
  widgetName: "BigBlueButton Conference"

  # The subtitle for BigBlueButton widgets that are generated by Dimension.
  widgetTitle: "Join the conference"

  # The avatar for BigBlueButton widgets that are generated by Dimension.
  # Usually this doen't need to be changed, however if your homeserver
  # is not able to reach t2bot.io then you should specify your own here.
  widgetAvatarUrl: "mxc://t2bot.io/be1650140620d8bb61a8cf5baeb05f24a734434c"
